# Цей файл environment.yml використовується для створення конкретного середовища Conda,
# яке містить всі необхідні залежності для проекту. Використовуючи цей файл, ви можете легко
# відтворити середовище на іншому комп'ютері або для інших користувачів, що забезпечує
# консистенцію роботи проекту. Щоб використати цей файл, вам потрібно встановити Conda,
# яка є менеджером пакетів і середовищ. Після встановлення Conda відкрийте термінал і виконайте
# наступну команду для створення середовища з ім'ям 'base':
# conda env create -f environment.yml
# Якщо ви хочете створити середовище з іншим ім'ям, змініть 'base' на обране вами ім'я.
# Після створення середовища активуйте його за допомогою команди:
# conda activate base
# Тепер ви можете запускати код, який залежить від пакетів і версій, вказаних у цьому файлі.
# Для запуску Jupyter Notebook, що містить мій проект, виконайте команду:
# jupyter notebook
# Ваш браузер автоматично відкриється з Jupyter Notebook. Ви можете імпортувати файл .ipynb,
# який був надісланий вам, через інтерфейс Jupyter, використовуючи опцію 'Upload' або
# перетягнувши файл у вікно браузера з Jupyter Notebook.

name: base
channels:
  - defaults
dependencies:
  - python=3.11.5
  - matplotlib=3.7.2
  - numpy=1.24.3
  - ipywidgets=8.0.4
  - voila=0.5.5
  - notebook=6.5.4
  - ipython=8.15.0